// THIS IS AN AUTOGENERATED FILE

#ifndef BATTERYFULL_H
#define BATTERYFULL_H

#include "../icon.h"

class BatteryFull : public Icon {
    public:
        BatteryFull() : Icon(32, 32) {};
        const uint16_t* getBitmap();
        void draw(TFT_eSprite* sprite);
};

#endif
