// THIS IS AN AUTOGENERATED FILE

#ifndef HOT_H
#define HOT_H

#include "../icon.h"

class Hot : public Icon {
    public:
        Hot() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
