// THIS IS AN AUTOGENERATED FILE

#ifndef LEFTARROW_H
#define LEFTARROW_H

#include "../icon.h"

class LeftArrow : public Icon {
    public:
        LeftArrow() : Icon(32, 32) {};
        const uint16_t* getBitmap();
        void draw(TFT_eSprite* sprite);
};

#endif
