// THIS IS AN AUTOGENERATED FILE

#ifndef RGB0_H
#define RGB0_H

#include "../icon.h"

class RGB0 : public Icon {
    public:
        RGB0() : Icon(32, 32) {};
        const uint16_t* getBitmap();
        void draw(TFT_eSprite* sprite);
};

#endif
