// THIS IS AN AUTOGENERATED FILE

#ifndef RGB180_H
#define RGB180_H

#include "../icon.h"

class RGB180 : public Icon {
    public:
        RGB180() : Icon(32, 32) {};
        const uint16_t* getBitmap();
        void draw(TFT_eSprite* sprite);
};

#endif
