// THIS IS AN AUTOGENERATED FILE

#ifndef RGB120_H
#define RGB120_H

#include "../icon.h"

class RGB120 : public Icon {
    public:
        RGB120() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
