// THIS IS AN AUTOGENERATED FILE

#ifndef RGB150_H
#define RGB150_H

#include "../icon.h"

class RGB150 : public Icon {
    public:
        RGB150() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
