// THIS IS AN AUTOGENERATED FILE

#ifndef RGB240_H
#define RGB240_H

#include "../icon.h"

class RGB240 : public Icon {
    public:
        RGB240() : Icon(32, 32) {};
        const uint16_t* getBitmap();
        void draw(TFT_eSprite* sprite);
};

#endif
