// THIS IS AN AUTOGENERATED FILE

#ifndef RGB210_H
#define RGB210_H

#include "../icon.h"

class RGB210 : public Icon {
    public:
        RGB210() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
