// THIS IS AN AUTOGENERATED FILE

#ifndef RGB270_H
#define RGB270_H

#include "../icon.h"

class RGB270 : public Icon {
    public:
        RGB270() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
