// THIS IS AN AUTOGENERATED FILE

#ifndef RGB30_H
#define RGB30_H

#include "../icon.h"

class RGB30 : public Icon {
    public:
        RGB30() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
