// THIS IS AN AUTOGENERATED FILE

#ifndef RGB330_H
#define RGB330_H

#include "../icon.h"

class RGB330 : public Icon {
    public:
        RGB330() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
