// THIS IS AN AUTOGENERATED FILE

#ifndef RGB60_H
#define RGB60_H

#include "../icon.h"

class RGB60 : public Icon {
    public:
        RGB60() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
