// THIS IS AN AUTOGENERATED FILE

#ifndef RGB90_H
#define RGB90_H

#include "../icon.h"

class RGB90 : public Icon {
    public:
        RGB90() : Icon(32, 32) {};
        const uint16_t* getBitmap();
};

#endif
